# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

In [80]:
import re 
from pprint import pprint

In [70]:
documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]

In [71]:
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

## Задание 1

### Пункт 1. Пользователь по команде "*p*" может узнать владельца документа по его номеру

Примеры работы:

1.

```
Введите команду:
p

Введите номер документа:
10006
```
Результат:  
`Владелец документа: Аристарх Павлов`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

In [48]:
def document_owner():
    """
    функция позволяет узнать владельца документа по вводимому пользователем номеру
    """
    number_doc = input('Введите номер документа: ')
    for doc in documents:
        if doc['number'] == number_doc:
             return f'Владелец документа: {doc["name"]}'
    return f'Документ не найден в базе'

In [49]:
document_owner()

Введите номер документа: 10006


'Владелец документа: Аристарх Павлов'

In [105]:
document_owner()

Введите номер документа: 1234


'Документ не найден в базе'

### Пункт 2. Пользователь по команде "*s*" может по номеру документа узнать на какой полке он хранится

Примеры работы:

1.

```
Введите команду:
s

Введите номер документа:
10006
```
Результат:  
`Документ хранится на полке: 2`

2.
```
Введите команду:
p

Введите номер документа:
12345
```
Результат:  
`Документ не найден в базе`

In [7]:
# поскольку эру вункцию будем применять в следующей функции нецелесообразно вводить значение внутри функции
def shelf(number_docs):
    """
    функция позволяет узнать номер полки на которой находится документ, по вводимому пользователем номеру
    """
    for shelf, value in directories.items():
        if number_docs in value:
            return f'Документ на полке № {shelf}'
    return f'Такого документа нет'

In [108]:
number_docs = input('Введите номер документа чтобы узнать на какой он полке: ')
shelf(number_docs)

Введите номер документа чтобы узнать на какой он полке: 10006


'Документ на полке № 2'

### Пункт 3. Пользователь по команде "*l*" может увидеть полную информацию по всем документам

Пример работы:

```
Введите команду:
l
```

Результат:  
```
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [9]:
import re 

def complete_info():
    """
    функция позволяет вывести полную информацию по всем документам
    """
    for doc in documents:
        doc_type = doc['type']
        name = doc['name']
        doc_number = doc['number']
        number_shelf = re.sub(r'\D', '', shelf(doc_number))
        print(f"№: {doc_number}, тип: {doc_type}, владелец: {name}, полка хранения: {number_shelf}")  

In [10]:
complete_info()

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


### Пункт 4. Пользователь по команде "*ads*" может добавить новую полку

Примеры работы:

1.

```
Введите команду:
ads

Введите номер полки:
10
```
Результат:  
`Полка добавлена. Текущий перечень полок: 1, 2, 3, 10.`

2.
```
Введите команду:
ads

Введите номер полки:
1
```
Результат:  
`Такая полка уже существует. Текущий перечень полок: 1, 2, 3.`

In [11]:
def add_shelf():
    """
    функция преназначена добавить дополнительную полку 
    """
    number_new_shelf = input("Введите номер новой полки: ")
    if number_new_shelf not in directories:
        directories[number_new_shelf] = []
        return f"Полка добавлена. Текущий перечень полок {', '.join(list(directories.keys()))}"
    return f"Такая полка уже существует. Текущий перечень полок {', '.join(list(directories.keys()))}"

In [110]:
add_shelf()

Введите номер новой полки: 2


'Такая полка уже существует. Текущий перечень полок 1, 2, 3, 5, 6'



### Пункт 5. Пользователь по команде "*ds*" может удалить существующую полку из данных (только если она пустая)

Примеры работы:

1.

```
Введите команду:
ds

Введите номер полки:
3
```
Результат:  
`Полка удалена. Текущий перечень полок: 1, 2.`

2.
```
Введите команду:
ds

Введите номер полки:
1
```
Результат:  
`На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
ds

Введите номер полки:
4
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

In [13]:
def del_shelf():
    """
    функция преназначена удалить существующую полку из данных (только если она пустая)
    """
    number_del_shelf = input("Введите номер удаляемой полки: ")
    if number_del_shelf in directories:
        if directories[number_del_shelf] != []:
            return f"На полке есть документы, удалите их перед удалением полки. " \
                   f"Текущий перечень полок: {', '.join(list(directories.keys()))}"
        else:
            del directories[number_del_shelf]
            return f"Полка удалена. Текущий перечень полок: {', '.join(list(directories.keys()))}"
    return f"Такой полки не существует. Текущий перечень полок {', '.join(list(directories.keys()))}"

In [111]:
del_shelf()

Введите номер удаляемой полки: 6


'Полка удалена. Текущий перечень полок: 1, 2, 3, 5'

## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [93]:
def add_doc():
    """
    функция для добавления нового документа
    """
    doc_number = input("Введите номер документа: ")
    doc_type = input("Введите тип документа: ")
    doc_owner = input("Введите владельца документа: ")
    number_shelf = input("Введите номер полки: ")
    # Проверяем существование полки    
    if number_shelf not in directories:
        return print(f"Такой полки не существует. Добавьте полку командой as. \nТекущий список документов:"), complete_info()
    # Создаем словарь нового документа
    new_doc = dict(type = doc_type, number = doc_number, name = doc_owner)
    # Добавляем документ в список документов
    documents.append(new_doc)
    # Добавляем документ на необходимую полку
    directories[number_shelf] += [doc_number]
    return print(f"Документ успешно добавлен. \nТекущий список документов:"), complete_info()

In [94]:
add_doc()

Введите номер документа: 45
Введите тип документа: 45
Введите владельца документа: 45
Введите номер полки: 45
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
№: 45, тип: 45, владелец: 45, полка хранения: 
№: 45, тип: 45, владелец: 45, полка хранения: 


(None, None)

In [81]:
pprint(directories)

{'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['42']}


### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2

```

In [68]:
def del_doc():
    now_documents = documents.copy()
    doc_number = input("Введите номер документа, который хотите удалить: ")
    for doc in now_documents:
        if doc['number'] == doc_number:
            documents.remove(doc)
            return print(f"Документ удален. \nТекущий список документов:"), complete_info()
    return print(f"Документ не найден в базе. \nТекущий список документов:"), complete_info()

In [72]:
del_doc()

Введите номер документа, который хотите удалить: 4
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


(None, None)



### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

In [98]:
def move_doc():
    doc_number = input("Введите номер документа,который хоитите переместить: ")
    number_shelf = input("Введите номер полки на которую хотите переместить документ: ")
    if number_shelf not in directories:
        return print(f"Такой полки не существует. \nТекущий список документов:"), complete_info()
    for shelf, value in directories.items():
        if doc_number in value:
            directories[number_shelf] += [doc_number]
            value.remove(doc_number)
            return print(f"Документ перемещен. \nТекущий список документов:"), complete_info()
    return print(f"Документ не найден в базе. \nТекущий список документов:"), complete_info()

In [84]:
move_doc()

Введите номер документа,который хоитите переместить: 10006
Введите номер полки на которую хотите переместить документ: 5
Такой полки не существует. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3


(None, None)

In [85]:
move_doc()

Введите номер документа,который хоитите переместить: 10006
Введите номер полки на которую хотите переместить документ: 3
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3


(None, None)

In [86]:
pprint(directories)

{'1': ['2207 876234', '11-2'], '2': [], '3': ['42', '10006']}


In [103]:
# реализуем главную функцию
def main(instruction):
    if instruction == 'p':
        print(document_owner())
    elif instruction == 'l':
        complete_info()
    elif instruction == 's':
        number_docs = input('Введите номер документа чтобы узнать на какой он полке: ')
        print(shelf(number_docs))
    elif instruction == 'ads':
        print(add_shelf())
    elif instruction == 'ds':
        print(del_shelf())
    elif instruction == 'ad':
        add_doc()
    elif instruction == 'd':
        del_doc()
    elif instruction == 'm':
        move_doc()        
    else:
        print('Введена не верная команда.')

In [104]:
while True:
    instruction = input ('\nВведите команду: ').lower()
    if instruction == 'q':
        complete_info()
        break
    else:
        main(instruction)    


Введите команду: l
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
№: 46, тип: pass, владелец: lily, полка хранения: 2

Введите команду: в
Введена не верная команда.

Введите команду: d
Введите номер документа, который хотите удалить: 46
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 3
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3

Введите команду: m
Введите номер документа,который хоитите переместить: 10006
Введите номер полки на которую хотите переместить документ: 2
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.